[versions]
agp = "8.0.2"
expandable = "2.9.2"
glide = "4.15.1"
glide-transformations = "4.3.0"
gson = "2.10.1"
hilt-android-gradle-plugin = "2.46.1"
hilt-compiler = "2.46.1"
kotlin = "1.8.21"
core-ktx = "1.10.1"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
appcompat = "1.6.1"
kotlinx-coroutines-android = "1.7.2"
lifecycle-runtime-ktx = "2.6.1"
logging-interceptor = "5.0.0-alpha.11"
material = "1.9.0"
constraintlayout = "2.1.4"
navigation-fragment-ktx = "2.6.0"
navigation-safe-args-gradle-plugin = "2.6.0"
palette-ktx = "1.0.0"
photo-view = "2.3.0"
retrofit = "2.9.0"

[libraries]
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "palette-ktx" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
expandable = { module = "com.github.cachapa:ExpandableLayout", version.ref = "expandable" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-transformations = { module = "jp.wasabeef:glide-transformations", version.ref = "glide-transformations" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
hilt-dagger-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-compiler" }
hilt-dagger-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android-gradle-plugin" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-fragment-ktx" }
navigation-component = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation-safe-args-gradle-plugin" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
hilt-dagger = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt-android-gradle-plugin" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
navigation-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
photo-view = { module = "com.github.chrisbanes:PhotoView", version.ref = "photo-view" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

[bundles]

